[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
runOnSave = false
maxUploadSize = 200

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false
toolbarMode = "minimal"

[logger]
level = "warning"
